export type Episode = { id: string; number: number; title: string; titleTh: string; duration: string; thumbnail: string; views: number; updatedAt: string; hlsUrl?: string; };
export type Anime = { id: string; slug: string; title: string; titleTh: string; titleEn: string; description: string; cover: string; banner: string; year: number; season: string; episodesTotal: number; episodes: Episode[]; rating: number; views: number; genres: string[]; status: "กำลังฉาย" | "จบแล้ว" | "ยังไม่ฉาย"; studio: string; duration: string; featured?: boolean; trendingRank?: number; trailerYoutubeId?: string; trailerDubYoutubeId?: string; trailerThumbnail?: string; };
const HLS_DEMO = [
  "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
  "https://test-streams.mux.dev/bbb_30fps/bbb_30fps.m3u8",
  "https://test-streams.mux.dev/caminandes/caminandes.m3u8",
];
// ตั้งค่า NEXT_PUBLIC_HLS_BASE_URL ใน .env เพื่อชี้ไป R2/Cloudflare Stream จริง เช่น https://your.r2.dev/hls
// ตัวอย่าง: NEXT_PUBLIC_HLS_BASE_URL=https://your.r2.dev/hls -> /<slug>/ep-1/master.m3u8
export const HLS_BASE = process.env.NEXT_PUBLIC_HLS_BASE_URL || "";

export const animes: Anime[] = [
  {
    id: "1",
    slug: "solo-leveling-season-2",
    title: "Ore dake Level Up na Ken: Season 2 - Arise from the Shadow",
    titleTh: "โซโล่ เลเวลลิ่ง ซีซั่น 2: ตื่นจากเงา",
    titleEn: "Solo Leveling Season 2 -Arise from the Shadow-",
    description: "ซองจินอูกลับมาในฐานะฮันเตอร์แรงก์ S การต่อสู้กับดันเจี้ยนระดับภัยพิบัติและความลับของระบบกำลังถูกเปิดเผย อนิเมะแอคชั่นอันดับ 1 ที่ดัดแปลงจากเว็บตูนชื่อดัง",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx176496-9BDMjAZGEbq4.png",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/176496-5oY4k2NRqlYs.jpg",
    year: 2025,
    season: "ฤดูหนาว 2025",
    episodesTotal: 13,
    rating: 8.4,
    views: 4940000,
    genres: ["แอคชั่น", "ผจญภัย", "แฟนตาซี"],
    status: "จบแล้ว",
    studio: "A-1 Pictures",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "byJ7pxxhaDY",
    trailerDubYoutubeId: "byJ7pxxhaDY",
    trailerThumbnail: "https://i.ytimg.com/vi/byJ7pxxhaDY/hqdefault.jpg",
    featured: true,
    trendingRank: 1,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx176496-9BDMjAZGEbq4.png",
      views: 4940000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "2",
    slug: "frieren-beyond-journeys-end",
    title: "Sousou no Frieren",
    titleTh: "คำอธิษฐานในวันที่จากลา ฟรีเรน",
    titleEn: "Frieren: Beyond Journey’s End",
    description: "ฟรีเรน เอลฟ์สาวผู้มีชีวิตนับพันปี ออกเดินทางหลังปราบจอมมารเพื่อเข้าใจความหมายของเวลาและสายสัมพันธ์กับเพื่อนมนุษย์ อนิเมะแฟนตาซีดราม่าที่คว้ารางวัล Anime of the Year",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-qQTzQnEJJ3oB.jpg",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/154587-ivXNJ23SM1xB.jpg",
    year: 2023,
    season: "ฤดูใบไม้ร่วง 2023",
    episodesTotal: 28,
    rating: 9.1,
    views: 5185000,
    genres: ["ผจญภัย", "ดราม่า", "แฟนตาซี"],
    status: "จบแล้ว",
    studio: "MADHOUSE",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "tR8YH0G67Rk",
    trailerDubYoutubeId: "tR8YH0G67Rk",
    trailerThumbnail: "https://i.ytimg.com/vi/tR8YH0G67Rk/hqdefault.jpg",
    featured: true,
    trendingRank: 2,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-qQTzQnEJJ3oB.jpg",
      views: 5185000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "3",
    slug: "dandadan",
    title: "Dandadan",
    titleTh: "ดันดาดัน",
    titleEn: "DAN DA DAN",
    description: "โมโมะสาวมัธยมผู้เชื่อเรื่องผีและโอคารุนหนุ่มผู้เชื่อเรื่องเอเลี่ยน ต้องเผชิญทั้งวิญญาณและมนุษย์ต่างดาวพร้อมกัน อนิเมะแอคชั่นคอมเมดี้สุดคลั่งจาก Science SARU",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx171018-60q1B6GK2Ghb.jpg",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/171018-SpwPNAduszXl.jpg",
    year: 2024,
    season: "ฤดูใบไม้ร่วง 2024",
    episodesTotal: 12,
    rating: 8.3,
    views: 4905000,
    genres: ["แอคชั่น", "คอมเมดี้", "ดราม่า"],
    status: "จบแล้ว",
    studio: "Science SARU",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "rJo1MnsuxyY",
    trailerDubYoutubeId: "rJo1MnsuxyY",
    trailerThumbnail: "https://i.ytimg.com/vi/rJo1MnsuxyY/hqdefault.jpg",
    featured: true,
    trendingRank: 3,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx171018-60q1B6GK2Ghb.jpg",
      views: 4905000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "4",
    slug: "kaiju-no-8",
    title: "Kaijuu 8-gou",
    titleTh: "ไคจูหมายเลข 8",
    titleEn: "Kaiju No. 8",
    description: "ฮิบิโนะ คาฟก้า วัย 32 ปีฝันอยากเข้าหน่วยป้องกันไคจู แต่กลับกลายร่างเป็นไคจูหมายเลข 8 เสียเอง เขาจะปกปิดตัวตนและปกป้องมนุษยชาติได้อย่างไร",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx153288-25FBfFJzEQ5O.jpg",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/153288-JNsWuMPMAuJL.jpg",
    year: 2024,
    season: "ฤดูใบไม้ผลิ 2024",
    episodesTotal: 12,
    rating: 8.1,
    views: 4835000,
    genres: ["แอคชั่น", "ไซไฟ"],
    status: "จบแล้ว",
    studio: "Production I.G",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "7n_mFVPeApw",
    trailerDubYoutubeId: "7n_mFVPeApw",
    trailerThumbnail: "https://i.ytimg.com/vi/7n_mFVPeApw/hqdefault.jpg",
    trendingRank: 4,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx153288-25FBfFJzEQ5O.jpg",
      views: 4835000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "5",
    slug: "demon-slayer-hashira-training",
    title: "Kimetsu no Yaiba: Hashira Geiko-hen",
    titleTh: "ดาบพิฆาตอสูร ภาคการสั่งสอนของเสาหลัก",
    titleEn: "Demon Slayer: Kimetsu no Yaiba Hashira Training Arc",
    description: "ทันจิโร่และพรรคพวกเข้าสู่การฝึกพิเศษกับเสาหลักทั้ง 9 เพื่อเตรียมพร้อมศึกสุดท้ายกับมุซัน จากสตูดิโอ ufotable",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx166240-PBV7zukIHW7V.png",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/166240-YdxoEhrfwNk0.jpg",
    year: 2024,
    season: "ฤดูใบไม้ผลิ 2024",
    episodesTotal: 8,
    rating: 7.9,
    views: 4765000,
    genres: ["แอคชั่น", "ผจญภัย", "ดราม่า"],
    status: "จบแล้ว",
    studio: "ufotable",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "7w5Vfjozzb8",
    trailerDubYoutubeId: "7w5Vfjozzb8",
    trailerThumbnail: "https://i.ytimg.com/vi/7w5Vfjozzb8/hqdefault.jpg",
    trendingRank: 5,
    episodes: Array.from({ length: 8 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx166240-PBV7zukIHW7V.png",
      views: 4765000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "6",
    slug: "wind-breaker",
    title: "WIND BREAKER",
    titleTh: "วินด์ เบรกเกอร์",
    titleEn: "WIND BREAKER",
    description: "ซากุระ ฮารุกะต้องการเป็นที่หนึ่งจึงเข้าเรียนโรงเรียนฟูรินที่ขึ้นชื่อเรื่องนักเลง แต่กลับพบว่าพวกเขาคือผู้ปกป้องเมือง",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx163270-wboZJp0ybwVK.jpg",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/163270-fcjrqp3iKWdb.jpg",
    year: 2024,
    season: "ฤดูใบไม้ผลิ 2024",
    episodesTotal: 13,
    rating: 7.7,
    views: 4695000,
    genres: ["แอคชั่น", "คอมเมดี้", "ดราม่า"],
    status: "จบแล้ว",
    studio: "CloverWorks",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "k5qM1PoLmUc",
    trailerDubYoutubeId: "k5qM1PoLmUc",
    trailerThumbnail: "https://i.ytimg.com/vi/k5qM1PoLmUc/hqdefault.jpg",
    trendingRank: 6,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx163270-wboZJp0ybwVK.jpg",
      views: 4695000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "7",
    slug: "oshi-no-ko-season-2",
    title: "[Oshi no Ko] 2nd Season",
    titleTh: "เกิดใหม่เป็นลูกโอชิ ซีซั่น 2",
    titleEn: "OSHI NO KO Season 2",
    description: "อควาและรูบีก้าวเข้าสู่วงการบันเทิงเต็มตัว การแก้แค้นและความฝันในโลกไอดอลที่เต็มไปด้วยแสงและเงา",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx166531-dAL5MsqDHUkj.jpg",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/166531-vUu7iDwUkC67.jpg",
    year: 2024,
    season: "ฤดูร้อน 2024",
    episodesTotal: 13,
    rating: 8.5,
    views: 4975000,
    genres: ["ดราม่า", "ลึกลับ", "Psychological"],
    status: "จบแล้ว",
    studio: "Doga Kobo",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "QMuajQlx64c",
    trailerDubYoutubeId: "QMuajQlx64c",
    trailerThumbnail: "https://i.ytimg.com/vi/QMuajQlx64c/hqdefault.jpg",
    trendingRank: 7,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx166531-dAL5MsqDHUkj.jpg",
      views: 4975000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "8",
    slug: "mushoku-tensei-season-2",
    title: "Mushoku Tensei II: Isekai Ittara Honki Dasu",
    titleTh: "เกิดชาตินี้พี่ต้องเทพ ภาค 2",
    titleEn: "Mushoku Tensei: Jobless Reincarnation Season 2",
    description: "รูเดียสเริ่มต้นชีวิตในมหาวิทยาลัยเวทมนตร์และการผจญภัยบทใหม่ที่เต็มไปด้วยเวทมนตร์และความรัก",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx146065-IjirxRK26O03.png",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/146065-33RDijfuxLLk.jpg",
    year: 2023,
    season: "ฤดูร้อน 2023",
    episodesTotal: 13,
    rating: 8.1,
    views: 4835000,
    genres: ["ผจญภัย", "ดราม่า", "Ecchi"],
    status: "จบแล้ว",
    studio: "Studio Bind",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "ts5NGoDI1V0",
    trailerDubYoutubeId: "ts5NGoDI1V0",
    trailerThumbnail: "https://i.ytimg.com/vi/ts5NGoDI1V0/hqdefault.jpg",
    trendingRank: 8,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx146065-IjirxRK26O03.png",
      views: 4835000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "9",
    slug: "one-piece-egghead",
    title: "ONE PIECE",
    titleTh: "วันพีซ",
    titleEn: "ONE PIECE",
    description: "ลูฟี่และกลุ่มหมวกฟางออกเดินทางสู่เกาะเอ็กเฮดของดร.เวก้าพังค์ ความลับของศตวรรษที่ว่างเปล่ากำลังถูกเปิดเผย",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21-ELSYx3yMPcKM.jpg",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
    year: 1999,
    season: "ฤดูใบไม้ร่วง 1999",
    episodesTotal: 12,
    rating: 8.7,
    views: 5045000,
    genres: ["แอคชั่น", "ผจญภัย", "คอมเมดี้"],
    status: "กำลังฉาย",
    studio: "Toei Animation",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "S8_YwFLCh4U",
    trailerDubYoutubeId: "S8_YwFLCh4U",
    trailerThumbnail: "https://i.ytimg.com/vi/S8_YwFLCh4U/hqdefault.jpg",
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21-ELSYx3yMPcKM.jpg",
      views: 5045000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "10",
    slug: "jujutsu-kaisen-season-2",
    title: "Jujutsu Kaisen 2nd Season",
    titleTh: "มหาเวทย์ผนึกมาร ซีซั่น 2",
    titleEn: "JUJUTSU KAISEN Season 2",
    description: "เหตุการณ์ชิบูย่าที่เปลี่ยนโลกไสยศาสตร์ โกโจถูกผนึก สุคุนะตื่นขึ้น การต่อสู้ที่ดุเดือดที่สุดได้เริ่มต้น",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx145064-hSNRJM03pvv1.jpg",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/145064-esDtAY2He7sk.jpg",
    year: 2023,
    season: "ฤดูร้อน 2023",
    episodesTotal: 23,
    rating: 8.6,
    views: 5010000,
    genres: ["แอคชั่น", "ดราม่า", "เหนือธรรมชาติ"],
    status: "จบแล้ว",
    studio: "MAPPA",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "O6qVieflwqs",
    trailerDubYoutubeId: "O6qVieflwqs",
    trailerThumbnail: "https://i.ytimg.com/vi/O6qVieflwqs/hqdefault.jpg",
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx145064-hSNRJM03pvv1.jpg",
      views: 5010000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "11",
    slug: "spy-family-season-2",
    title: "SPY×FAMILY Season 2",
    titleTh: "สปาย x แฟมิลี ซีซั่น 2",
    titleEn: "SPY x FAMILY Season 2",
    description: "ครอบครัวฟอร์เจอร์กลับมาแล้ว ลอยด์ ยอร์ และอาเนียต้องเผชิญภารกิจใหม่ที่ทั้งฮาและอบอุ่นหัวใจ",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b158927-lfO85WVguYgc.png",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/158927-zXtbXUO5iKzX.jpg",
    year: 2023,
    season: "ฤดูใบไม้ร่วง 2023",
    episodesTotal: 12,
    rating: 8.0,
    views: 4800000,
    genres: ["แอคชั่น", "คอมเมดี้", "ชีวิตประจำวัน"],
    status: "จบแล้ว",
    studio: "WIT STUDIO",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "W2tMsaAVjD0",
    trailerDubYoutubeId: "W2tMsaAVjD0",
    trailerThumbnail: "https://i.ytimg.com/vi/W2tMsaAVjD0/hqdefault.jpg",
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b158927-lfO85WVguYgc.png",
      views: 4800000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
  {
    id: "12",
    slug: "attack-on-titan-final-season",
    title: "Shingeki no Kyojin: The Final Season",
    titleTh: "ผ่าพิภพไททัน เดอะ ไฟนอล ซีซั่น",
    titleEn: "Attack on Titan Final Season",
    description: "บทสรุปมหาสงครามระหว่างมนุษยชาติและไททัน เอเรนเลือกเส้นทางแห่งการทำลายล้างเพื่อปกป้องพวกพ้อง",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx110277-sKUNXAsWMNFw.jpg",
    banner: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/110277-iuGn6F5bK1U1.jpg",
    year: 2021,
    season: "ฤดูหนาว 2021",
    episodesTotal: 16,
    rating: 8.7,
    views: 5045000,
    genres: ["แอคชั่น", "ดราม่า", "แฟนตาซี"],
    status: "จบแล้ว",
    studio: "MAPPA",
    duration: "24 นาที/ตอน",
    trailerYoutubeId: "MUCN-JwUvbY",
    trailerDubYoutubeId: "MUCN-JwUvbY",
    trailerThumbnail: "https://i.ytimg.com/vi/MUCN-JwUvbY/hqdefault.jpg",
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ep-${i + 1}`,
      number: i + 1,
      title: `Episode ${i + 1}`,
      titleTh: `ตอนที่ ${i + 1}`,
      duration: "23:42",
      hlsUrl: HLS_DEMO[i % HLS_DEMO.length],
      thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx110277-sKUNXAsWMNFw.jpg",
      views: 5045000 - i * 18000,
      updatedAt: `2024-12-${String(10 + i).padStart(2, "0")}`,
    })),
  },
];

export const categories = ["ทั้งหมด","แอคชั่น","ผจญภัย","แฟนตาซี","ดราม่า","คอมเมดี้","ไซไฟ","โรงเรียน","โชเน็น","เหนือธรรมชาติ","ต่างโลก"] as const;
export const getAnimeBySlug = (slug: string) => animes.find((a) => a.slug === slug);
export const getTrending = () => animes.filter((a) => a.trendingRank).sort((a, b) => (a.trendingRank! - b.trendingRank!));
export const getFeatured = () => animes.filter((a) => a.featured);
export const getLatestEpisodes = () => { const eps: (Episode & { anime: Anime })[] = []; animes.forEach((anime) => { anime.episodes.slice(0, 2).forEach((ep) => eps.push({ ...ep, anime })); }); return eps.sort((a, b) => b.views - a.views).slice(0, 8); };
export const searchAnimes = (q: string) => { const lower = q.toLowerCase(); return animes.filter((a) => a.title.toLowerCase().includes(lower) || a.titleEn.toLowerCase().includes(lower) || a.titleTh.includes(q) || a.genres.some((g) => g.includes(q))); };
export const filterByCategory = (cat: string) => { if (cat === "ทั้งหมด") return animes; return animes.filter((a) => a.genres.includes(cat)); };